title: "Valay's Writeups"
description: "Detailed walkthroughs for TryHackMe (THM) rooms, CTFs, and cybersecurity challenges.
url: "https://valay-2004.github.io/THM-Writeups/" # Replace with your actual GitHub Pages URL
author: "Valay"
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: :compressed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    line_numbers: false
